version: "3.9"

services:
  app:
    build: .
    container_name: my-app
    ports:
      -   "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/mydb
      DB_USERNAME: user
      DB_PASSWORD: pass
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:latest
    container_name: my-db
    ##
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    networks:
      - my-network
    expose:
      - "5432"

networks:
  my-network:
    driver: bridge
