spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
  file:
    name: /logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

